Lab-1
Er4ik/nodejs-course pull request #4
Opened 2022-10-16 21:09 UTC by Er4ik

2022-10-17 19:29 UTC, nosovk requested changes
оно не может рабоать по определению. Добавь ссылку на задеплоенный эндпоинт.

2022-10-17 19:30 UTC, nosovk commented on .editorconfig
> +insert_final_newline = true
правило есть, а newline в файле нету

2022-10-17 19:31 UTC, nosovk commented on package.json
> +    "prettier": "prettier --check .",
я бы еще предложил использовать .gitignore как набор глобов для игнора

2022-10-17 19:32 UTC, nosovk commented on package.json
> +    "lint": "eslint --ext .js,.ts .",
для ts нужен build/watch/dev

2022-10-17 19:32 UTC, nosovk commented on package.json
> +    "*.{ts,md}": "prettier --write"
было в материалах что хуки не должны иметь сайд еффектов, в чате был пример почему

2022-10-17 19:33 UTC, nosovk commented on src/main.ts
> +export default function handler(req: any, res: any) {
у versel есть тайпинг, его и использовать

2022-10-17 19:33 UTC, nosovk commented on tsconfig.json
> +    "target": "es5",
почему?

2022-10-27 19:46 UTC, Er4ik commented
@nosovk  Link to endpoint - https://nodejs-course-fzdssau7b-er4ik.vercel.app/api

2022-10-30 11:03 UTC, nosovk commented on .github/workflows/main.yml
> +      - run: npm ci
тут забыт if
У нас кеш будет восстановлен, перед npm ci.
 После чего npm ci его удалит и скачает заново.
Чтобы корректно работало - нужно поставить if кеш есть, то npm ci запускать не нужно

2022-10-30 11:04 UTC, nosovk commented on .github/workflows/main.yml
> +      - run: npm run lint:fix
в ci не должно быть side effects на код, поэтому запускать тут fix нельзя

2022-10-30 11:05 UTC, nosovk commented on package.json
> +    "lint:fix": "npm run lint -- --fix --ignore-path .gitignore",
ignore-path уже есть в lint, зачем еще раз его писать?

2022-10-30 11:44 UTC, Er4ik commented
https://nodejs-course-o7haomf4z-er4ik.vercel.app/api

2022-10-30 16:50 UTC, nosovk commented on package.json
> +    "prettier:fix": "prettier --write .",
а для prettier:fix не вызвается же npm script. Зачем тут убрал --ignore-path .gitignore?

2022-10-30 16:58 UTC, nosovk commented
merge

2022-10-30 16:58 UTC, merged